CREATE ROLE IF NOT EXISTS TF_DEPLOY;
GRANT ROLE TF_DEPLOY TO ROLE SYSADMIN;

GRANT CREATE DATABASE    ON ACCOUNT TO ROLE TF_DEPLOY;
GRANT CREATE WAREHOUSE   ON ACCOUNT TO ROLE TF_DEPLOY;
GRANT CREATE ROLE        ON ACCOUNT TO ROLE TF_DEPLOY;
GRANT CREATE USER        ON ACCOUNT TO ROLE TF_DEPLOY;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE TF_DEPLOY;

GRANT MANAGE GRANTS ON ACCOUNT TO ROLE TF_DEPLOY;

USE ROLE TF_DEPLOY;
CREATE WAREHOUSE TF_SMOKE WITH WAREHOUSE_SIZE = 'XSMALL' INITIALLY_SUSPENDED = TRUE;
DROP WAREHOUSE TF_SMOKE;

SHOW GRANTS TO ROLE TF_DEPLOY;

GRANT ROLE TF_DEPLOY TO USER AKSHAYBUDHALKAR7

SELECT CURRENT_USER();