CREATE TABLE IF NOT EXISTS RAW_DB.LANDING.HOSTS (
  HOST_ID        NUMBER(38,0),
  HOST_NAME      VARCHAR(200),
  HOST_SINCE     DATE,
  IS_SUPERHOST   BOOLEAN,
  RESPONSE_RATE  NUMBER(5,2),
  CREATED_AT     TIMESTAMP_NTZ,
  _FILE_NAME     VARCHAR(500),
  _LOAD_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Managed by schemachange';
