CREATE TABLE IF NOT EXISTS RAW_DB.LANDING.LISTINGS (
  LISTING_ID       NUMBER(38,0),
  HOST_ID          NUMBER(38,0),
  PROPERTY_TYPE    VARCHAR(100),
  ROOM_TYPE        VARCHAR(100),
  CITY             VARCHAR(200),
  COUNTRY          VARCHAR(200),
  ACCOMMODATES     NUMBER(38,0),
  BEDROOMS         NUMBER(38,0),
  BATHROOMS        NUMBER(38,0),
  PRICE_PER_NIGHT  NUMBER(12,2),
  CREATED_AT       TIMESTAMP_NTZ,
  _FILE_NAME       VARCHAR(500),
  _LOAD_TS         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Managed by schemachange';