CREATE TABLE IF NOT EXISTS RAW_DB.LANDING.BOOKINGS (
  BOOKING_ID      VARCHAR(36),
  LISTING_ID      NUMBER(38,0),
  BOOKING_DATE    DATE,
  NIGHTS_BOOKED   NUMBER(38,0),
  BOOKING_AMOUNT  NUMBER(12,2),
  CLEANING_FEE    NUMBER(12,2),
  SERVICE_FEE     NUMBER(12,2),
  BOOKING_STATUS  VARCHAR(50),
  CREATED_AT      TIMESTAMP_NTZ,
  _FILE_NAME      VARCHAR(500),
  _LOAD_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Managed by schemachange';