CREATE PIPE IF NOT EXISTS RAW_DB.LANDING.PIPE_HOSTS
  AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB.LANDING.HOSTS
  (HOST_ID, HOST_NAME, HOST_SINCE, IS_SUPERHOST, RESPONSE_RATE, CREATED_AT, _FILE_NAME)
FROM (
  SELECT $1, $2, $3, $4, $5, $6, METADATA$FILENAME
  FROM @RAW_DB.LANDING.STG_HOSTS
)
FILE_FORMAT = (FORMAT_NAME = RAW_DB.LANDING.FF_CSV);

CREATE PIPE IF NOT EXISTS RAW_DB.LANDING.PIPE_LISTINGS
  AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB.LANDING.LISTINGS
  (LISTING_ID, HOST_ID, PROPERTY_TYPE, ROOM_TYPE, CITY, COUNTRY,
   ACCOMMODATES, BEDROOMS, BATHROOMS, PRICE_PER_NIGHT, CREATED_AT, _FILE_NAME)
FROM (
  SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, METADATA$FILENAME
  FROM @RAW_DB.LANDING.STG_LISTINGS
)
FILE_FORMAT = (FORMAT_NAME = RAW_DB.LANDING.FF_CSV);

CREATE PIPE IF NOT EXISTS RAW_DB.LANDING.PIPE_BOOKINGS
  AUTO_INGEST = TRUE
AS
COPY INTO RAW_DB.LANDING.BOOKINGS
  (BOOKING_ID, LISTING_ID, BOOKING_DATE, NIGHTS_BOOKED, BOOKING_AMOUNT,
   CLEANING_FEE, SERVICE_FEE, BOOKING_STATUS, CREATED_AT, _FILE_NAME)
FROM (
  SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, METADATA$FILENAME
  FROM @RAW_DB.LANDING.STG_BOOKINGS
)
FILE_FORMAT = (FORMAT_NAME = RAW_DB.LANDING.FF_CSV);