name: Terraform Plan

on:
  push:
    branches:
      - 'initial-setup'
  pull_request:
    branches: [main]


permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::656559336744:role/airbnb-pipeline-snowflake-github-actions
          aws-region: us-east-1

    #   - run: aws sts get-caller-identity
    #   - run: aws s3 ls airbnb-pipeline-tf-656559336744-us-east-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: infra


      - run: terraform plan
        working-directory: infra
        env:
          SNOWFLAKE_ORGANIZATION_NAME: ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
          SNOWFLAKE_ACCOUNT_NAME: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
          SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
          SNOWFLAKE_ROLE: TF_DEPLOY


    